dist: bionic

language: go

go:
  - 1.13.x

git:
  depth: 1

notifications:
  email: wishwa.perera.93@gmail.com

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled